trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Step 1: Install .NET 8.0 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 8.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x' # Installs the latest .NET 8.0 SDK available

# Step 2: Restore dependencies
- script: dotnet restore
  displayName: 'Restore dependencies'

# Step 3: Build the project
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build the project'

# Step 4: Publish the project
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the project'

# Step 5: Publish the build artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Step 6: Deploy to Azure App Service
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional Subscription(4)(5942bc94-5c1a-42d5-977c-e8656aac87c4)'
    appType: 'webApp'
    WebAppName: 'mytestdata'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
