# ASP.NET Core Pipeline
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Restore NuGet packages
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x' # Specify the .NET SDK version matching your project
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  displayName: 'Restore Dependencies'

# Build the application
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build Application'

# Run tests (optional)
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run Unit Tests'

# Publish the application
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Application'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# Deploy to Azure App Service
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Professional Subscription(7)(5942bc94-5c1a-42d5-977c-e8656aac87c4)'
    appType: 'webApp'
    WebAppName: 'jbj'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
